In [2]:
import numpy as np
A= np.array([[1,-4], [1,-4]])
B = np.array([[1,-8],[-8,2]])
print("A+B= ", A+B)


A+B=  [[  2 -12]
 [ -7  -2]]


In [5]:
import numpy as np
A = np.array([[2,3,1],[4,5,1]])
B = np.array([[-1, 2],[4,-2],[3,6]])
print(A)
print(20*"-")
print(B)
print(20*"-")
print("A*B= ", np.dot(A,B))
print(20*"-")
print("B*A= ", np.dot(A,B))

[[2 3 1]
 [4 5 1]]
--------------------
[[-1  2]
 [ 4 -2]
 [ 3  6]]
--------------------
A*B=  [[13  4]
 [19  4]]
--------------------
B*A=  [[13  4]
 [19  4]]


## tinh dinh thuc va nghich dao cua ma tran
### linalg = linear algebra

In [8]:
A= np.array([[1,3], [5,6]]) 
B = np.array([[4,6], [-8, 12]]) 
print(B)
detA = np.linalg.det(A)
Ainv = np.linalg.inv(A)
detB= np.linalg.det(B)
print(20*"-")
print("Nghich dao cua ma tran A: ", detA)
print(20*"-")
print("Nghich dao cua ma tran B: ", detB)


[[ 4  6]
 [-8 12]]
--------------------
Nghich dao cua ma tran A:  -8.999999999999998
--------------------
Nghich dao cua ma tran B:  95.99999999999999
