In [8]:
import sympy as sp
# x^2020 + 3*x^3-1
x = sp.Symbol('x')
fx= x**2020 + 3*x**3-1
fx

x**2020 + 3*x**3 - 1

In [9]:
sp.diff(fx, x)

2020*x**2019 + 9*x**2

In [10]:
gx = x/(x+1)
gx

x/(x + 1)

In [11]:
print("g'(x)= ",sp.simplify(sp.diff(gx,x)))

g'(x)=  (x + 1)**(-2)


In [12]:
fx = sp.exp(x)/x
sp.diff(fx,x)

exp(x)/x - exp(x)/x**2

In [13]:
gx = 3*sp.log(x,2) - x*sp.log(x)
gx
print("g'(x)= ", sp.simplify(sp.diff(gx, x)))

g'(x)=  -log(x) - 1 + 3/(x*log(2))


## 1.3 Các hàm phổ biến


In [19]:
import numpy as np
a= np.arange(1,100,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
np.round(np.var(a), 2)

np.float64(816.67)

np.round(np.std(a), 2)

np.min(a)

### 1.5 Các phương thức thống kê của numpy array

In [24]:
x = np.arange(1,11)

In [26]:
x.sum()

np.int64(55)

In [27]:
x.mean()

np.float64(5.5)

In [28]:
x.std()

np.float64(2.8722813232690143)

In [29]:
x.var()

np.float64(8.25)

In [30]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [34]:
y = np.arange(1,10)
y = y.reshape(3,-1)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
print(y.mean(axis=0))
print(y.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


In [38]:
sorted(set(x))

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10)]

In [40]:
a = np.array([2,-3,4.5,7,0,1,-1])
a.argmax()

np.int64(3)