In [1]:
import numpy as np
np.__version__

'2.3.5'

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.linspace(-10, 10, 20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [5]:
list1 = [[1,2,3],[4,5,6], [7,8,9]]

In [6]:
list1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
list1[0][0]

1

In [8]:
arr2d= np.array(list1)

In [10]:
arr2d.ndim

2

In [14]:
arrZeros2d = np.zeros((2,3))

In [15]:
type(arrZeros2d[0][0])

numpy.float64

# định dạng lại hình dạng của mảng

In [21]:
a2 = np.arange(15)

In [22]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# tạo số random ngẫu nhiên
data = np.random.randn(3,5)
data

array([[ 0.59119469, -0.276638  , -0.29929933, -0.46012353,  0.67048338],
       [ 0.03738658, -0.23206093, -1.32807615, -0.44058041,  1.59153123],
       [ 1.43604709, -0.56719891, -0.97678951,  1.86432733, -2.15777531]])

In [26]:
np.mean(data)

np.float64(-0.03650478585214591)

In [27]:
%time for i in range(1000): np.arange(1000000)*2

CPU times: total: 13.8 s
Wall time: 15 s


In [30]:
%time for i in range(1000): list(range(10000))*2

CPU times: total: 656 ms
Wall time: 756 ms


In [53]:
a = np.array([[1,2,3], [3,4,7]])
a

array([[1, 2, 3],
       [3, 4, 7]])

In [48]:
b = np.append(a, [4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [55]:
b = np.append(a, [[3,5,6]], axis=0)
b

array([[1, 2, 3],
       [3, 4, 7],
       [3, 5, 6]])

In [56]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
a = np.arange(1,11)
print(a.sum())

55


In [61]:
a.mean()

np.float64(5.5)

In [63]:
a_mean = a.mean()
a-a_mean
(a-a_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [65]:
dev(a-a_mean)**2

NameError: name 'dev' is not defined

In [67]:
dev.sum()/a.size

NameError: name 'dev' is not defined

In [68]:
# phương sai
a.var()

np.float64(8.25)

In [69]:
# độ lệnh chuẩn
np.sqrt(a.var())

np.float64(2.8722813232690143)

In [70]:
a.std()

np.float64(2.8722813232690143)

In [71]:
#tong tich luy
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [74]:
a= np.arange(1,7)

In [75]:
a

array([1, 2, 3, 4, 5, 6])

In [76]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
#Thống lê từng hàng và cột
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [84]:
a.mean(axis=1)

array([2., 5.])

## Tạo số ngẫu nhiên trong Numpy

In [92]:
np.random.seed(42)
np.random.randint(10)

6

### Hàm được sử dung thường xuyên

In [98]:
a= np.arange(6)

In [99]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [100]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [114]:
a = np.arange(100)

In [115]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [116]:
a.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [118]:
np.median(a)

np.float64(49.5)

In [119]:
np.sum(a)

np.int64(4950)

In [120]:
np.round(np.var(a),2)

np.float64(833.25)

In [121]:
np.argmin(a)

np.int64(0)