<a href="https://colab.research.google.com/github/Duchuy-05/SamSung_Inovation_Campus_2026/blob/master/Exercise_14_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
a1 = np.array([0,10,20,30,40,50])
a1[[1,3,4]]

array([10, 30, 40])

In [4]:
a2= np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
a2[1] #lấy toàn bộ hàng 1

array([40, 50, 60])

In [12]:
a2[2]= [45,55,65] #gán hàng số 2 mảng mới
a2

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [16]:
a2[[0,2], [0,1]] # lấy theo tập hợp các chiều [[h,h],[c,c]]

array([10, 55])

In [18]:
a = np.array([1,2,3,4,5,6,7])

a[a>3]

array([4, 5, 6, 7])

In [19]:
a[a%2==0]

array([2, 4, 6])

In [20]:
b1= np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [26]:
b1[:3]

array([ 0, 10, 20])

In [27]:
b1[2:]

array([20, 30, 40, 50])

## Lát cắt trên mảng 2 chiều

In [32]:
arr2d = np.arange(1,10).reshape(3,-1)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2d[:2, 1:]  #Cắt từ dòng đầu đến dòng 2, từ cột 1 đén cuối

array([[2, 3],
       [5, 6]])

## Mảng String và Boolean

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [36]:
names == 'Bob' #Kiển tra các phần tiwr có giá trị bằng 'Bob'

array([ True, False, False,  True, False, False, False])

In [37]:
names[names=='Bob']  #Lọc

array(['Bob', 'Bob'], dtype='<U4')

In [39]:
arr = np.empty((8,4))
arr

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [40]:
for i in range (8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [41]:
arr[[4,3,0,6]] #tách các hàng 4,3,0,6 đi từ trên xuống

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [46]:
arr2 = np.arange(20)
arrMask = (arr2%5==0)
arr2[arrMask]

array([ 0,  5, 10, 15])

In [51]:
arrMask2= (arr2 >= 10)
arr2[arrMask & arrMask2]

array([10, 15])

In [54]:
arr=np.random.randn(6,3)
arr

array([[-1.06614549,  2.16627472, -0.01529912],
       [ 0.30618099,  0.0157515 , -0.34346665],
       [ 0.06517231,  0.06778933, -0.64286066],
       [-0.42096481, -0.01823189,  0.59187288],
       [-0.8295063 ,  1.55046548,  0.55394553],
       [-0.57186109,  0.44300572,  0.29500937]])

In [57]:
arr.T

array([[-1.06614549,  0.30618099,  0.06517231, -0.42096481, -0.8295063 ,
        -0.57186109],
       [ 2.16627472,  0.0157515 ,  0.06778933, -0.01823189,  1.55046548,
         0.44300572],
       [-0.01529912, -0.34346665, -0.64286066,  0.59187288,  0.55394553,
         0.29500937]])

In [56]:
#Nhân ma trân không sử dụng toán tử
#sử dụng np.dot(A,B)
np.dot(arr.T, arr)

array([[ 2.42697761, -3.83210685, -1.00811193],
       [-3.83210685,  7.29811931,  0.896642  ],
       [-1.00811193,  0.896642  ,  1.27567291]])